# Generated by Django 2.2.1 on 2019-05-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('weightage', models.IntegerField(default=0)),
            ],
        ),
    ]
