# Generated by Django 2.2.1 on 2019-05-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_title', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('Orange', 'Orange'), ('Green', 'Green')], default='Blue', max_length=30)),
                ('average_rating', models.IntegerField(default=0)),
                ('general_comment', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Audit_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audits')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Process_Checklist')),
            ],
        ),
    ]
