# Generated by Django 2.2.1 on 2019-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audit_items_audits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audits',
            name='status',
            field=models.CharField(choices=[('Blue Less Than 70 %', 'Blue'), ('Red', 'Red'), ('Orange', 'Orange'), ('Green', 'Green')], default='Blue', max_length=30),
        ),
    ]
