# Generated by Django 2.2.1 on 2019-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20190508_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audits',
            name='status',
            field=models.CharField(choices=[('Blue', 'Blue Less Than 59 %'), ('Red', 'Red 60 %'), ('Orange', 'Orange 75 %'), ('Green', 'Green 90%')], default='Blue', max_length=30),
        ),
    ]
