# Generated by Django 2.2.1 on 2019-05-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20190508_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_checklist',
            name='group',
            field=models.CharField(choices=[('Code Quality', 'Code Quality'), ('Processes', 'Processes'), ('Quality Assurance', 'Quality Assurance')], default='General', max_length=30),
        ),
    ]
