# Generated by Django 2.2.1 on 2019-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_process_checklist_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_items',
            name='comment',
            field=models.TextField(),
        ),
    ]
