# Generated by Django 2.2.1 on 2019-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('team_size', models.IntegerField(default=0)),
                ('technology_stack', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('git_hub_link', models.URLField()),
            ],
        ),
    ]
